<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="progam_web_page" nsURI="platform:/plugin/tdt4250.program_web_page.model/model/program_web_page.ecore"
    nsPrefix="program_web_page">
  <eClassifiers xsi:type="ecore:EClass" name="Programme">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specialisations" upperBound="-1"
        eType="#//Specialisation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semesters" upperBound="-1"
        eType="#//Semester" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Specialisation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semesters" lowerBound="1"
        upperBound="11" eType="#//Semester" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Semester">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semseterNumb" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courseGroups" upperBound="-1"
        eType="#//CourseGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" upperBound="-1"
        eType="#//Course"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CourseGroup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxGroupCredits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" upperBound="-1"
        eType="#//Course"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mandatoryType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Course">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="#//degreeLevel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="degreeLevel">
    <eLiterals name="firstLevel"/>
    <eLiterals name="secondLevel" value="1"/>
    <eLiterals name="thirdLEvel" value="2"/>
    <eLiterals name="higherLevel" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NTNU">
    <eStructuralFeatures xsi:type="ecore:EReference" name="programmes" upperBound="-1"
        eType="#//Programme" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" upperBound="-1"
        eType="#//Course" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
